name: Build iOS IPA

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Environment
        run: |
          echo "Mac bulut sunucusu başarıyla çalışıyor!"
          xcodebuild -version
          ls -la
