name: Build iOS IPA

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create IPA Package Structure
        run: |
          mkdir -p Payload
          # index.html dosyanı ve web dosyalarını Payload içine kopyalıyoruz
          cp index.html Payload/
          
          # Zip haline getirip uzantısını .ipa yapıyoruz
          zip -r SelTube-1.0.ipa Payload
          ls -la

      - name: Save IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SelTube-IPA
          path: SelTube-1.0.ipa
